---
name: Build and Push Image JAVA
on:
#   push:
#     branches: [ main ]
  workflow_dispatch: {}
jobs:

  extract-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from changelog
        id: get_version
        run: |
          VERSION=$(grep -m1 -oP '(?<=## \[)[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md)
          echo "Version found: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Print version from previous job
        run: |
          echo "Version is: ${{ needs.extract-version.outputs.app_version }}"

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Validate Docker Build and Run Locally
        run: |
          echo -e "\e[32mDocker build\e[0m"
          docker build -t mi-app:1.0 .           
          docker images   
          echo -e "\e[32mdocker ps\e[0m"
          docker ps
          echo -e "\e[32mdocker ps -a\e[0m"
          docker ps -a  
          echo -e "\e[32mdocker run -a\e[0m"
          docker run -d --name mi-contenedor -p 8081:8081 -e SERVER_ADDRESS=0.0.0.0 mi-app:1.0  
          echo -e "\e[32mdocker ps II\e[0m"
          docker ps
          echo -e "\e[32mdocker ps -a II\e[0m"
          docker ps -a   
          sleep 20         
          echo -e "\e[32mVALIDAR\e[0m"      
          docker logs mi-contenedor                  
          curl http://localhost:8081/weatherForecast          