---
name: Build and Push Image JAVA
on:
#   push:
#     branches: [ main ]
  workflow_dispatch: {}
jobs:

  extract-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from changelog
        id: get_version
        run: |
          VERSION=$(grep -m1 -oP '(?<=## \[)[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md)
          echo "Version found: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Print version from previous job
        run: |
          echo "Version is: ${{ needs.extract-version.outputs.app_version }}"

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Validate Docker Build and Run Locally
        run: |
          echo -e "\e[32mDocker build\e[0m"
          docker build -t mi-app:1.0 .           
          docker images   
          echo -e "\e[32mdocker ps\e[0m"
          docker ps
          echo -e "\e[32mdocker ps -a\e[0m"
          docker ps -a  
          echo -e "\e[32mdocker run -a\e[0m"
          docker run -d --name mi-contenedor -p 8081:8081 -e SERVER_ADDRESS=0.0.0.0 mi-app:1.0  
          echo -e "\e[32mdocker ps II\e[0m"
          docker ps
          echo -e "\e[32mdocker ps -a II\e[0m"
          docker ps -a   
          sleep 20         
          echo -e "\e[32mVALIDAR\e[0m"      
          docker logs mi-contenedor                  
          curl http://localhost:8081/weatherForecast        

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, Tag, and Push the Image to Amazon ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: sesion2tecylabjava
      #     IMAGE_TAG: ${{ needs.extract-version.outputs.app_version }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      #     docker images 
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - name: Configure ACR credentials
      #   uses: azure/docker-login@v2
      #   with:
      #     login-server: testsesion2.azurecr.io # default: index.docker.io
      #     username: ${{ secrets.AZURE_ACR_ACCESS_USER }}
      #     password: ${{ secrets.AZURE_ACR_ACCESS_PASS }}  

      # - name: Build & Push image
      #   env:
      #     ACR_REGISTRY: testsesion2.azurecr.io
      #     ACR_REPOSITORY: minimalapi
      #     IMAGE_TAG: ${{ needs.extract-version.outputs.app_version }}      
      #   run: |
      #     echo -e "\e[32mBuild componente\e[0m"
      #     docker build -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG .
      #     echo -e "\e[32mPush componente\e[0m"
      #     docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
      #     docker images

      - uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}' # Replace with the name of your GitHub Actions secret
      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
      - name: Push Docker Image to Artifact Registry
        env:          
          AR_REGISTRY: us-east1-docker.pkg.dev
          AR_REPOSITORY: sesion2tecylabjava
          PROJECT_ID: credenciales-364703
          IMAGE_NAME: sesion2tecylabjava
          IMAGE_TAG: ${{ needs.extract-version.outputs.app_version }} 
        run: |
          echo -e "\e[32mBuild componente\e[0m"
          docker build -t $AR_REGISTRY/$AR_REPOSITORY:$IMAGE_TAG .                  
          docker tag $AR_REGISTRY/$AR_REPOSITORY:$IMAGE_TAG us-east1-docker.pkg.dev/$PROJECT_ID/testtecylab/$IMAGE_NAME:$IMAGE_TAG
          docker images
          docker push us-east1-docker.pkg.dev/$PROJECT_ID/testtecylab/$IMAGE_NAME:$IMAGE_TAG
          docker images